### PR TITLE
update hazard.py - more discrete ip grab, cleaner imports, changes to config cmmnts.

### PR DESCRIPTION
**Pull request by mte0**
- added utilities.tk api (less obvious than ipinfo.io)
     - tries to use utilities.tk, otherwise uses ipinfo.io

- cleaned up imports (reduces storage and visual mess)

- minor changes to config comments

### CODE REVIEW

**Comment by Resisst** [comment]
A lot of this is just extra code however the comments are quite helpful.

**Comment by PandoricGalaxy** [comment]
Looks good! But rdimo is offline since few days even I'm waiting for him to accept my pulll request in webhook protector

**Comment by mte0** [comment]
> A lot of this is just extra code however the comments are quite helpful.

yeah fair enough, ive gone ahead and shortened it down quite a fair bit :)

**Comment by Rdimo** [comment]
seems nice but only thing I rly see any value in is the new link, since ye its alot more obvious that a link steals ur ip if it has **ipinfo** in it rather than **utilities.tk**, the try except is only usable if its run without network but it handles that before that function is even ran so not rly necessary. Imports are messier imo but some people prefer that so ye not rly anything I can say there. Looks good otherwise

**Comment by mte0** [comment]
grrr can u reopen or do i make new pr

**Pull request closed without merging**
