### PR TITLE
added a check to history grabber

### PR DESCRIPTION
**Pull request by Smug246**
you need to have google closed when grabbing otherwise you'll receive a permission error saying the database is locked. also added some more profiles to get the token from

### CODE REVIEW

**Comment by Resisst** [comment]
really the history file needs to be copied to a different directory then read from instead of closing chrome

**Comment by addi00000** [comment]
Yeah there is no reason to work inside the chrome directory directly

**Comment by Rdimo** [comment]
ye as the other 2 said, to avoid getting file in use error I just copy the db file and work with it in the temp folder instead

**Comment by Rdimo** [comment]
I also think that all tokens store in the default folder no matter what to avoid being logged out from discord when using different google accounts

**Comment by Smug246** [comment]
makes sense mb

**Comment by Rdimo** [comment]
> makes sense mb

lmao no worries

**Comment by addi00000** [comment]
The only reason you might want do do this is because chrome doesn't load the history data from the current session(s) into the history file until the session(s) are closed. This is probably the same for other features.

**Pull request closed without merging**
