### PR TITLE
fixed im cool

### PR DESCRIPTION
**Pull request by GodFather227**

### CODE REVIEW

**Comment by Smug246** [comment]
this shit ass

**Comment by GodFather227** [comment]
> this shit ass

nigga how

**Comment by GodFather227** [comment]
and rdimo deadass told me to make this pull

**Comment by GodFather227** [comment]
@Rdimo its cool as shit that ur updating but can you merge my pr like u fucking said u would. thx ddy

**Comment by Smug246** [comment]
pretty ass pull ngl😜

**Comment by timmywag** [comment]
😠

**Comment by GodFather227** [comment]
> pretty ass pull ngl😜

I’m ngl I still didn’t fix the wrong path so imma close this 💀

**Pull request closed without merging**
