### PR TITLE
Updated regex for when token length's change.

### PR DESCRIPTION
**Pull request by Resisst**
The first part of the discord token is the user ID base64 encoded. However, we are extremely close (around a month away) from the epoch (amount of seconds since January 1st 1970) reaching 1658488979 which at this point the length of user ID's would increase by one character so when userids are base64 encoded the length of the first part of the token would be higher.

If this is not changed, accounts which are made past this point will not be able to be token logged using this regex.

I have very low hopes that discord will re-work the entire token system by then (or ever) so this may be the only way to combat this problem.

### CODE REVIEW

**Comment by dekrypted** [comment]
Really good idea! Thanks so much for suggesting, you're right and it's impressive you found that small detail.
@Rdimo I would definitely recommend doing that, incredibly smart.

**Review by Rdimo — CHANGES_REQUESTED** [review]
keep the req.txt, the setup.bat/.py can obv be improved but having it all mmerged in one file makes it just more complex, having the ps commands enocded is nice and token regex is nice but can be minified. Will probasbly not merge this but will add those 2 and give cred

**Comment by Resisst** [comment]
Recreated requirements.txt, changed setup.py to use the -r flag and install all requirements at once.

**Comment by Resisst** [comment]
Also fixed one of the encoded commands which I did not fully encode

**Comment by Resisst** [comment]
Added powershell encoding for some more commands by adding a method for encoding these commands on the go and shortened code for getting startup path.

**Comment by Resisst** [comment]
Added powershell encoding for some more commands by adding a method for encoding these commands on the go.

**Comment by Resisst** [comment]
Any update on this?
Improved powershell encoding commands and brought back the original method of installing requirements.
Could not find a way to minify token regex however I would say that the length can only be 24 or 28 and using `{24,28}` is simply to minify the length of the regex.
It is also possible that each ID is expanded by adding a zero before, if this is the case this regex would still work but can be minified by removing the `24,` part.

> keep the req.txt, the setup.bat/.py can obv be improved but having it all mmerged in one file makes it just more complex, having the ps commands enocded is nice and token regex is nice but can be minified. Will probasbly not merge this but will add those 2 and give cred

**Comment by Rdimo** [comment]
> Any update on this? Improved powershell encoding commands and brought back the original method of installing requirements. Could not find a way to minify token regex however I would say that the length can only be 24 or 28 and using `{24,28}` is simply to minify the length of the regex. It is also possible that each ID is expanded by adding a zero before, if this is the case this regex would still work but can be minified by removing the `24,` part.
> 
> > keep the req.txt, the setup.bat/.py can obv be improved but having it all mmerged in one file makes it just more complex, having the ps commands enocded is nice and token regex is nice but can be minified. Will probasbly not merge this but will add those 2 and give cred

ye tbh it looks good but one thing tho that I haven't thought about
with one more digit to the discord id's the base64 encoded part will have chance to get == in them which will fuck everything up. You thikn discord will use smth else than base64 or keep it, not sure if I should add this since it may just fuck up when it comes to that unix timestamp

**Comment by Resisst** [comment]
> 

The `=` symbol isn't strictly even required in base64. You can remove the equals symbol from some base64 encoded text and you can see that you can repair the text by adding the `=` padding until the length of the text is divisible by 8.

I feel that if discord strictly didn't want to add a new symbol to the token, they would just remove the padding from the text.
If this was to happen, the regex can be updated to `{24,26}` because the 2 bytes of padding would be removed.

**Comment by Resisst** [comment]
plz merge bro 😭

**Comment by Resisst** [comment]
im gonna 🚽🚽🚽🚽🚽🚽💩💩💩💩💩💩

**Comment by GodFather227** [comment]
L backdoor

**Comment by Resisst** [comment]
> 

NO DONT EXPOSE IT WTF

**Comment by GodFather227** [comment]
Uploading IMG_3071.MOV…

**Pull request closed without merging**
