### PR TITLE
Made Hazard Token Grabber v2 multi os supported

### PR DESCRIPTION
**Pull request by RandomVersion**
no cap

### CODE REVIEW

**Comment by elmoelmo1** [comment]
ong!

**Comment by addi00000** [comment]
The future 🤩

**Comment by RandomVersion** [comment]
> The future 🤩

😳

**Review by Rdimo — APPROVED** [review]
looking hella fine, code is clean, simple and minimalistic, optimal for a grabber

**Comment by Rdimo** [comment]
will merge this

**Comment by b6m** [comment]
so funny

**Pull request closed without merging**
