### PR TITLE
Builder added

### PR DESCRIPTION
**Pull request by p3tt3**
I make a builder for hazard, sorry if the code is not perfect but is my first python code, sorry if there are bug,soon I am going to fix all the bug

### CODE REVIEW

**Comment by GodFather227** [comment]
> I make a builder for hazard, sorry if the code is not perfect but is my first python code

The injection would no longer work ☹️

**Comment by timmywag** [comment]
0 bonkas 😢

**Comment by p3tt3** [comment]
> > I make a builder for hazard, sorry if the code is not perfect but is my first python code
> 
> The injection would no longer work ☹️

no,this is only a builder,the injection is on the main.py file so then the injection will continue to work

**Comment by timmywag** [comment]
bad pull 😠

**Comment by GodFather227** [comment]
> > > I make a builder for hazard, sorry if the code is not perfect but is my first python code
> > 
> > 
> > The injection would no longer work ☹️
> 
> no,this is only a builder,the injection is on the main.py file so then the injection will continue to work

I’ll check Hol up

**Comment by p3tt3** [comment]
> I make a builder for hazard, sorry if the code is not perfect but is my first python code, sorry if there are bug,soon I am going to fix all the bug

I fixed the bug, idk if the fixed file is in this pull request, but it is on my repository so you can check it on my repository if you can't see the fixed version here

**Comment by Resisst** [comment]
no.

**Comment by GodFather227** [comment]
☡☻☲☟☞☸☸ ☳☦☤☤☞

**Pull request closed without merging**
